modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/therealm18/oc2rc/issues"
license = "MIT"

[[mods]]
modId = "oc2rc"
version = "${file.jarVersion}"
displayName = "OC2R: Components"
authors = "The Realm 18 Studios"
description = '''
OC2R Components all the extra components you need.
'''

[[dependencies.oc2rc]]
modId = "forge"
mandatory = true
versionRange = "[40.4.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.oc2rc]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.1"
ordering = "NONE"
side = "BOTH"
[[dependencies.oc2rc]]
modId = "oc2r"
mandatory = true
versionRange = "[2.2.4,)"
side = "BOTH"
ordering = "AFTER"
[[dependencies.oc2rc]]
modId = "oc2rcore"
mandatory = true
versionRange = "[1.0.0,)"
side = "BOTH"
ordering = "AFTER"
